// Programmatic location SEO dataset — facts only.
// One entry per city; copy (titles/headlines/intros) is generated from these
// facts + the per-state profile in src/lib/locations.ts. Visible footprint is
// the 9 states where ProTech holds its own contractor license (TX/KY/MO/OH/
// PA/MD/WV). Coordinates feed LocalBusiness schema — keep them accurate.

export interface CityFact {
  city: string;
  citySlug: string;
  county: string;
  lat: number;
  lng: number;
  surroundingCities: string[];
}

export interface StateProfile {
  state: string;
  stateSlug: string;
  stateAbbr: string;
  /** Used by StateServicePageTemplate's weatherContext prop. */
  weatherContext: string;
  /** Short climate-challenge phrase woven into city intros. */
  climate: string;
  /** Geographic descriptor, e.g. "from the Gulf Coast to the North Texas plains". */
  region: string;
  /** Regionally appropriate materials phrase. */
  materials: string;
}

export const STATE_PROFILES: Record<string, StateProfile> = {
  texas: {
    state: 'Texas',
    stateSlug: 'texas',
    stateAbbr: 'TX',
    weatherContext: 'intense summer heat, severe hailstorms, and Gulf Coast hurricanes',
    climate: 'blistering summer heat, damaging spring hailstorms, and high winds',
    region: 'from the Gulf Coast to the North Texas plains',
    materials: 'cool-roof-rated shingles, impact-resistant Class 4 shingles, and metal roofing',
  },
  ohio: {
    state: 'Ohio',
    stateSlug: 'ohio',
    stateAbbr: 'OH',
    weatherContext: 'lake-effect snow, ice dams, and summer thunderstorms',
    climate: 'lake-effect snow, freeze-thaw cycles, and severe summer storms',
    region: 'across the Buckeye State',
    materials: 'architectural shingles, ice-and-water shield, and proper attic ventilation',
  },
  missouri: {
    state: 'Missouri',
    stateSlug: 'missouri',
    stateAbbr: 'MO',
    weatherContext: 'tornado-season storms, damaging hail, and winter ice',
    climate: 'tornado-season winds, large hail, and winter snow and ice',
    region: 'from the Ozarks to the I-70 corridor',
    materials: 'impact-resistant Class 4 shingles and reinforced flashing',
  },
  kentucky: {
    state: 'Kentucky',
    stateSlug: 'kentucky',
    stateAbbr: 'KY',
    weatherContext: 'severe spring storms, summer humidity, and winter ice',
    climate: 'severe spring thunderstorms, humid summers, and winter ice storms',
    region: 'across the Bluegrass State',
    materials: 'architectural shingles and upgraded ventilation systems',
  },
  pennsylvania: {
    state: 'Pennsylvania',
    stateSlug: 'pennsylvania',
    stateAbbr: 'PA',
    weatherContext: 'harsh winters, ice dams, and heavy snowfall',
    climate: "nor'easters, heavy snow loads, and freeze-thaw cycles",
    region: 'from Philadelphia to the western ridges',
    materials: 'architectural shingles, flat-roof membranes, and ice-and-water shield',
  },
  maryland: {
    state: 'Maryland',
    stateSlug: 'maryland',
    stateAbbr: 'MD',
    weatherContext: "nor'easters, humid summers, and winter ice",
    climate: "humid summers, severe thunderstorms, nor'easters, and winter ice",
    region: 'across the Mid-Atlantic',
    materials: 'architectural shingles, standing-seam metal, and coastal-grade systems',
  },
  'west-virginia': {
    state: 'West Virginia',
    stateSlug: 'west-virginia',
    stateAbbr: 'WV',
    weatherContext: 'heavy mountain snowfall, ice, and spring storms',
    climate: 'heavy mountain snowfall, freeze-thaw cycles, and spring storms',
    region: 'throughout the Mountain State',
    materials: 'steep-slope shingle systems, metal roofing, and ice protection',
  },
  'south-carolina': {
    state: 'South Carolina',
    stateSlug: 'south-carolina',
    stateAbbr: 'SC',
    weatherContext: 'Atlantic hurricanes, humid summer heat, and severe thunderstorms',
    climate: 'Atlantic hurricanes, humid summers, and severe thunderstorms',
    region: 'from the Lowcountry coast to the Upstate',
    materials: 'hurricane-rated shingles, impact-resistant systems, and proper ventilation',
  },
  indiana: {
    state: 'Indiana',
    stateSlug: 'indiana',
    stateAbbr: 'IN',
    weatherContext: 'severe thunderstorms, hail, and winter snow and ice',
    climate: 'severe spring storms, summer hail, and winter snow and ice',
    region: 'across the Hoosier State',
    materials: 'impact-resistant architectural shingles and ice-and-water shield',
  },
};

export const CITY_DATA: Record<string, CityFact[]> = {
  texas: [
    { city: 'Houston', citySlug: 'houston', county: 'Harris County', lat: 29.7604, lng: -95.3698, surroundingCities: ['Pasadena', 'Pearland', 'Sugar Land', 'Baytown', 'Missouri City'] },
    { city: 'San Antonio', citySlug: 'san-antonio', county: 'Bexar County', lat: 29.4241, lng: -98.4936, surroundingCities: ['New Braunfels', 'Schertz', 'Converse', 'Universal City', 'Live Oak'] },
    { city: 'Dallas', citySlug: 'dallas', county: 'Dallas County', lat: 32.7767, lng: -96.7970, surroundingCities: ['Irving', 'Garland', 'Mesquite', 'Richardson', 'Carrollton'] },
    { city: 'Austin', citySlug: 'austin', county: 'Travis County', lat: 30.2672, lng: -97.7431, surroundingCities: ['Round Rock', 'Cedar Park', 'Pflugerville', 'Georgetown', 'San Marcos'] },
    { city: 'Fort Worth', citySlug: 'fort-worth', county: 'Tarrant County', lat: 32.7555, lng: -97.3308, surroundingCities: ['Arlington', 'North Richland Hills', 'Keller', 'Haltom City', 'Benbrook'] },
    { city: 'El Paso', citySlug: 'el-paso', county: 'El Paso County', lat: 31.7619, lng: -106.4850, surroundingCities: ['Socorro', 'Horizon City', 'San Elizario', 'Anthony'] },
    { city: 'Arlington', citySlug: 'arlington', county: 'Tarrant County', lat: 32.7357, lng: -97.1081, surroundingCities: ['Grand Prairie', 'Mansfield', 'Fort Worth', 'Kennedale', 'Pantego'] },
    { city: 'Corpus Christi', citySlug: 'corpus-christi', county: 'Nueces County', lat: 27.8006, lng: -97.3964, surroundingCities: ['Portland', 'Robstown', 'Aransas Pass', 'Ingleside'] },
    { city: 'Plano', citySlug: 'plano', county: 'Collin County', lat: 33.0198, lng: -96.6989, surroundingCities: ['Frisco', 'Richardson', 'Allen', 'McKinney', 'Carrollton'] },
    { city: 'Laredo', citySlug: 'laredo', county: 'Webb County', lat: 27.5306, lng: -99.4803, surroundingCities: ['Rio Bravo', 'El Cenizo'] },
    { city: 'Lubbock', citySlug: 'lubbock', county: 'Lubbock County', lat: 33.5779, lng: -101.8552, surroundingCities: ['Wolfforth', 'Slaton', 'Shallowater', 'Idalou'] },
    { city: 'Irving', citySlug: 'irving', county: 'Dallas County', lat: 32.8140, lng: -96.9489, surroundingCities: ['Grand Prairie', 'Dallas', 'Coppell', 'Euless', 'Farmers Branch'] },
    { city: 'Garland', citySlug: 'garland', county: 'Dallas County', lat: 32.9126, lng: -96.6389, surroundingCities: ['Mesquite', 'Rowlett', 'Richardson', 'Sachse', 'Dallas'] },
    { city: 'Frisco', citySlug: 'frisco', county: 'Collin County', lat: 33.1507, lng: -96.8236, surroundingCities: ['Plano', 'McKinney', 'Little Elm', 'The Colony', 'Prosper'] },
    { city: 'McKinney', citySlug: 'mckinney', county: 'Collin County', lat: 33.1972, lng: -96.6398, surroundingCities: ['Frisco', 'Allen', 'Plano', 'Prosper', 'Melissa'] },
    { city: 'Grand Prairie', citySlug: 'grand-prairie', county: 'Dallas County', lat: 32.7460, lng: -96.9978, surroundingCities: ['Arlington', 'Irving', 'Mansfield', 'Cedar Hill', 'Duncanville'] },
    { city: 'Amarillo', citySlug: 'amarillo', county: 'Potter County', lat: 35.2220, lng: -101.8313, surroundingCities: ['Canyon', 'Bushland'] },
    { city: 'Brownsville', citySlug: 'brownsville', county: 'Cameron County', lat: 25.9017, lng: -97.4975, surroundingCities: ['Harlingen', 'San Benito', 'Los Fresnos', 'Port Isabel'] },
    { city: 'McAllen', citySlug: 'mcallen', county: 'Hidalgo County', lat: 26.2034, lng: -98.2300, surroundingCities: ['Edinburg', 'Mission', 'Pharr', 'Mercedes', 'Weslaco'] },
    { city: 'Killeen', citySlug: 'killeen', county: 'Bell County', lat: 31.1171, lng: -97.7278, surroundingCities: ['Temple', 'Harker Heights', 'Copperas Cove', 'Belton'] },
    { city: 'Denton', citySlug: 'denton', county: 'Denton County', lat: 33.2148, lng: -97.1331, surroundingCities: ['Lewisville', 'Flower Mound', 'Corinth', 'Sanger', 'Krum'] },
    { city: 'Pasadena', citySlug: 'pasadena', county: 'Harris County', lat: 29.6911, lng: -95.2091, surroundingCities: ['Houston', 'Deer Park', 'South Houston', 'La Porte', 'Baytown'] },
    { city: 'Mesquite', citySlug: 'mesquite', county: 'Dallas County', lat: 32.7668, lng: -96.5992, surroundingCities: ['Garland', 'Balch Springs', 'Sunnyvale', 'Dallas', 'Forney'] },
    { city: 'Midland', citySlug: 'midland', county: 'Midland County', lat: 31.9974, lng: -102.0779, surroundingCities: ['Odessa', 'Big Spring'] },
    { city: 'Carrollton', citySlug: 'carrollton', county: 'Dallas County', lat: 32.9756, lng: -96.8900, surroundingCities: ['Farmers Branch', 'Addison', 'Coppell', 'Plano', 'Lewisville'] },
    { city: 'Waco', citySlug: 'waco', county: 'McLennan County', lat: 31.5493, lng: -97.1467, surroundingCities: ['Bellmead', 'Hewitt', 'Woodway', 'Robinson', 'Lacy-Lakeview'] },
    { city: 'Odessa', citySlug: 'odessa', county: 'Ector County', lat: 31.8457, lng: -102.3676, surroundingCities: ['Midland', 'Gardendale'] },
    { city: 'Round Rock', citySlug: 'round-rock', county: 'Williamson County', lat: 30.5083, lng: -97.6789, surroundingCities: ['Austin', 'Pflugerville', 'Cedar Park', 'Georgetown', 'Hutto'] },
    { city: 'Sugar Land', citySlug: 'sugar-land', county: 'Fort Bend County', lat: 29.6197, lng: -95.6349, surroundingCities: ['Missouri City', 'Stafford', 'Richmond', 'Rosenberg', 'Houston'] },
    { city: 'Pearland', citySlug: 'pearland', county: 'Brazoria County', lat: 29.5636, lng: -95.2860, surroundingCities: ['Friendswood', 'Houston', 'Alvin', 'Manvel', 'League City'] },
    { city: 'College Station', citySlug: 'college-station', county: 'Brazos County', lat: 30.6280, lng: -96.3344, surroundingCities: ['Bryan', 'Navasota'] },
    { city: 'The Woodlands', citySlug: 'the-woodlands', county: 'Montgomery County', lat: 30.1658, lng: -95.4613, surroundingCities: ['Conroe', 'Spring', 'Shenandoah', 'Oak Ridge North'] },
    { city: 'League City', citySlug: 'league-city', county: 'Galveston County', lat: 29.5075, lng: -95.0949, surroundingCities: ['Friendswood', 'Webster', 'Dickinson', 'Texas City', 'Pearland'] },
    { city: 'Allen', citySlug: 'allen', county: 'Collin County', lat: 33.1032, lng: -96.6706, surroundingCities: ['McKinney', 'Plano', 'Frisco', 'Fairview', 'Wylie'] },
    { city: 'Lewisville', citySlug: 'lewisville', county: 'Denton County', lat: 33.0462, lng: -96.9942, surroundingCities: ['Flower Mound', 'Carrollton', 'The Colony', 'Coppell', 'Highland Village'] },
    { city: 'Richardson', citySlug: 'richardson', county: 'Dallas County', lat: 32.9483, lng: -96.7299, surroundingCities: ['Plano', 'Garland', 'Dallas', 'Addison', 'Murphy'] },
    { city: 'Tyler', citySlug: 'tyler', county: 'Smith County', lat: 32.3513, lng: -95.3011, surroundingCities: ['Whitehouse', 'Lindale', 'Bullard', 'Chandler'] },
    { city: 'Wichita Falls', citySlug: 'wichita-falls', county: 'Wichita County', lat: 33.9137, lng: -98.4934, surroundingCities: ['Burkburnett', 'Iowa Park'] },
    { city: 'Edinburg', citySlug: 'edinburg', county: 'Hidalgo County', lat: 26.3017, lng: -98.1633, surroundingCities: ['McAllen', 'Pharr', 'Mission', 'Weslaco', 'San Juan'] },
    { city: 'Mission', citySlug: 'mission', county: 'Hidalgo County', lat: 26.2159, lng: -98.3253, surroundingCities: ['McAllen', 'Pharr', 'Edinburg', 'Alton', 'Palmview'] },
    { city: 'San Angelo', citySlug: 'san-angelo', county: 'Tom Green County', lat: 31.4638, lng: -100.4370, surroundingCities: ['Grape Creek', 'Christoval'] },
    { city: 'Longview', citySlug: 'longview', county: 'Gregg County', lat: 32.5007, lng: -94.7405, surroundingCities: ['Kilgore', 'Marshall', 'Henderson', 'White Oak'] },
    { city: 'Pharr', citySlug: 'pharr', county: 'Hidalgo County', lat: 26.1948, lng: -98.1836, surroundingCities: ['McAllen', 'San Juan', 'Edinburg', 'Mission', 'Hidalgo'] },
    { city: 'Bryan', citySlug: 'bryan', county: 'Brazos County', lat: 30.6744, lng: -96.3700, surroundingCities: ['College Station', 'Navasota'] },
    { city: 'Baytown', citySlug: 'baytown', county: 'Harris County', lat: 29.7355, lng: -94.9774, surroundingCities: ['La Porte', 'Mont Belvieu', 'Deer Park', 'Channelview', 'Pasadena'] },
    { city: 'Pflugerville', citySlug: 'pflugerville', county: 'Travis County', lat: 30.4394, lng: -97.6200, surroundingCities: ['Round Rock', 'Austin', 'Hutto', 'Manor'] },
    { city: 'Temple', citySlug: 'temple', county: 'Bell County', lat: 31.0982, lng: -97.3428, surroundingCities: ['Belton', 'Killeen', 'Harker Heights', 'Troy'] },
    { city: 'Missouri City', citySlug: 'missouri-city', county: 'Fort Bend County', lat: 29.6186, lng: -95.5377, surroundingCities: ['Sugar Land', 'Stafford', 'Houston', 'Pearland', 'Richmond'] },
    { city: 'Flower Mound', citySlug: 'flower-mound', county: 'Denton County', lat: 33.0146, lng: -97.0969, surroundingCities: ['Lewisville', 'Grapevine', 'Coppell', 'Highland Village', 'Argyle'] },
    { city: 'New Braunfels', citySlug: 'new-braunfels', county: 'Comal County', lat: 29.7030, lng: -98.1245, surroundingCities: ['San Marcos', 'Schertz', 'Seguin', 'Cibolo', 'San Antonio'] },
    { city: 'Conroe', citySlug: 'conroe', county: 'Montgomery County', lat: 30.3119, lng: -95.4561, surroundingCities: ['The Woodlands', 'Willis', 'Montgomery', 'Spring'] },
    { city: 'Cedar Park', citySlug: 'cedar-park', county: 'Williamson County', lat: 30.5052, lng: -97.8203, surroundingCities: ['Leander', 'Round Rock', 'Austin', 'Georgetown'] },
    { city: 'Mansfield', citySlug: 'mansfield', county: 'Tarrant County', lat: 32.5632, lng: -97.1417, surroundingCities: ['Arlington', 'Grand Prairie', 'Kennedale', 'Burleson', 'Midlothian'] },
    { city: 'Georgetown', citySlug: 'georgetown', county: 'Williamson County', lat: 30.6333, lng: -97.6770, surroundingCities: ['Round Rock', 'Cedar Park', 'Leander', 'Hutto', 'Jarrell'] },
    { city: 'Harlingen', citySlug: 'harlingen', county: 'Cameron County', lat: 26.1906, lng: -97.6961, surroundingCities: ['San Benito', 'Brownsville', 'La Feria', 'Weslaco'] },
  ],
  ohio: [
    { city: 'Columbus', citySlug: 'columbus', county: 'Franklin County', lat: 39.9612, lng: -82.9988, surroundingCities: ['Dublin', 'Westerville', 'Grove City', 'Hilliard', 'Gahanna'] },
    { city: 'Cleveland', citySlug: 'cleveland', county: 'Cuyahoga County', lat: 41.4993, lng: -81.6944, surroundingCities: ['Parma', 'Lakewood', 'Euclid', 'Cleveland Heights', 'Shaker Heights'] },
    { city: 'Cincinnati', citySlug: 'cincinnati', county: 'Hamilton County', lat: 39.1031, lng: -84.5120, surroundingCities: ['Norwood', 'Fairfield', 'Mason', 'Hamilton', 'Middletown'] },
    { city: 'Toledo', citySlug: 'toledo', county: 'Lucas County', lat: 41.6528, lng: -83.5379, surroundingCities: ['Bowling Green', 'Maumee', 'Sylvania', 'Perrysburg', 'Oregon'] },
    { city: 'Akron', citySlug: 'akron', county: 'Summit County', lat: 41.0814, lng: -81.5190, surroundingCities: ['Cuyahoga Falls', 'Stow', 'Green', 'Barberton', 'Tallmadge'] },
    { city: 'Dayton', citySlug: 'dayton', county: 'Montgomery County', lat: 39.7589, lng: -84.1916, surroundingCities: ['Kettering', 'Huber Heights', 'Beavercreek', 'Fairborn', 'Centerville'] },
    { city: 'Parma', citySlug: 'parma', county: 'Cuyahoga County', lat: 41.4047, lng: -81.7229, surroundingCities: ['Cleveland', 'Parma Heights', 'Brooklyn', 'Seven Hills', 'North Royalton'] },
    { city: 'Canton', citySlug: 'canton', county: 'Stark County', lat: 40.7989, lng: -81.3784, surroundingCities: ['Massillon', 'North Canton', 'Alliance', 'Green', 'Louisville'] },
    { city: 'Lorain', citySlug: 'lorain', county: 'Lorain County', lat: 41.4528, lng: -82.1824, surroundingCities: ['Elyria', 'Avon Lake', 'Sheffield Lake', 'Amherst', 'North Ridgeville'] },
    { city: 'Hamilton', citySlug: 'hamilton', county: 'Butler County', lat: 39.3995, lng: -84.5613, surroundingCities: ['Fairfield', 'Middletown', 'Cincinnati', 'Mason', 'Oxford'] },
    { city: 'Youngstown', citySlug: 'youngstown', county: 'Mahoning County', lat: 41.0998, lng: -80.6495, surroundingCities: ['Boardman', 'Austintown', 'Warren', 'Niles', 'Canfield'] },
    { city: 'Springfield', citySlug: 'springfield', county: 'Clark County', lat: 39.9242, lng: -83.8088, surroundingCities: ['Dayton', 'Beavercreek', 'Fairborn', 'Xenia', 'Urbana'] },
    { city: 'Kettering', citySlug: 'kettering', county: 'Montgomery County', lat: 39.6895, lng: -84.1688, surroundingCities: ['Dayton', 'Centerville', 'Beavercreek', 'Oakwood', 'Moraine'] },
    { city: 'Elyria', citySlug: 'elyria', county: 'Lorain County', lat: 41.3683, lng: -82.1077, surroundingCities: ['Lorain', 'North Ridgeville', 'Avon', 'Amherst', 'Grafton'] },
    { city: 'Middletown', citySlug: 'middletown', county: 'Butler County', lat: 39.5151, lng: -84.3983, surroundingCities: ['Hamilton', 'Franklin', 'Monroe', 'Trenton', 'Springboro'] },
    { city: 'Cuyahoga Falls', citySlug: 'cuyahoga-falls', county: 'Summit County', lat: 41.1339, lng: -81.4846, surroundingCities: ['Akron', 'Stow', 'Tallmadge', 'Munroe Falls', 'Hudson'] },
    { city: 'Newark', citySlug: 'newark', county: 'Licking County', lat: 40.0581, lng: -82.4013, surroundingCities: ['Heath', 'Granville', 'Pataskala', 'Zanesville', 'Reynoldsburg'] },
    { city: 'Lakewood', citySlug: 'lakewood', county: 'Cuyahoga County', lat: 41.4820, lng: -81.7982, surroundingCities: ['Cleveland', 'Rocky River', 'Westlake', 'Fairview Park', 'Bay Village'] },
    { city: 'Dublin', citySlug: 'dublin', county: 'Franklin County', lat: 40.0992, lng: -83.1141, surroundingCities: ['Columbus', 'Hilliard', 'Worthington', 'Powell', 'Westerville'] },
    { city: 'Euclid', citySlug: 'euclid', county: 'Cuyahoga County', lat: 41.5931, lng: -81.5268, surroundingCities: ['Cleveland', 'Willowick', 'Mentor', 'Wickliffe', 'South Euclid'] },
    { city: 'Mansfield', citySlug: 'mansfield', county: 'Richland County', lat: 40.7584, lng: -82.5154, surroundingCities: ['Ontario', 'Ashland', 'Shelby', 'Lexington', 'Bucyrus'] },
    { city: 'Mentor', citySlug: 'mentor', county: 'Lake County', lat: 41.6662, lng: -81.3396, surroundingCities: ['Willoughby', 'Painesville', 'Eastlake', 'Kirtland', 'Wickliffe'] },
    { city: 'Beavercreek', citySlug: 'beavercreek', county: 'Greene County', lat: 39.7092, lng: -84.0633, surroundingCities: ['Dayton', 'Fairborn', 'Kettering', 'Xenia', 'Centerville'] },
    { city: 'Strongsville', citySlug: 'strongsville', county: 'Cuyahoga County', lat: 41.3145, lng: -81.8357, surroundingCities: ['North Royalton', 'Brunswick', 'Berea', 'Middleburg Heights', 'Brook Park'] },
    { city: 'Fairfield', citySlug: 'fairfield', county: 'Butler County', lat: 39.3454, lng: -84.5603, surroundingCities: ['Hamilton', 'Cincinnati', 'Mason', 'West Chester', 'Forest Park'] },
    { city: 'Delaware', citySlug: 'delaware', county: 'Delaware County', lat: 40.2987, lng: -83.0680, surroundingCities: ['Powell', 'Westerville', 'Marysville', 'Sunbury', 'Columbus'] },
    { city: 'Cleveland Heights', citySlug: 'cleveland-heights', county: 'Cuyahoga County', lat: 41.5201, lng: -81.5562, surroundingCities: ['Cleveland', 'Shaker Heights', 'University Heights', 'South Euclid', 'East Cleveland'] },
    { city: 'Huber Heights', citySlug: 'huber-heights', county: 'Montgomery County', lat: 39.8442, lng: -84.1247, surroundingCities: ['Dayton', 'Fairborn', 'Vandalia', 'Riverside', 'Tipp City'] },
    { city: 'Grove City', citySlug: 'grove-city', county: 'Franklin County', lat: 39.8814, lng: -83.0930, surroundingCities: ['Columbus', 'Hilliard', 'Galloway', 'Obetz', 'Groveport'] },
    { city: 'Lancaster', citySlug: 'lancaster', county: 'Fairfield County', lat: 39.7137, lng: -82.5993, surroundingCities: ['Pickerington', 'Reynoldsburg', 'Baltimore', 'Logan', 'Newark'] },
    { city: 'Reynoldsburg', citySlug: 'reynoldsburg', county: 'Franklin County', lat: 39.9548, lng: -82.8121, surroundingCities: ['Columbus', 'Pickerington', 'Pataskala', 'Gahanna', 'Whitehall'] },
    { city: 'Findlay', citySlug: 'findlay', county: 'Hancock County', lat: 41.0442, lng: -83.6499, surroundingCities: ['Fostoria', 'Tiffin', 'Bowling Green', 'Bluffton', 'Carey'] },
    { city: 'Warren', citySlug: 'warren', county: 'Trumbull County', lat: 41.2376, lng: -80.8184, surroundingCities: ['Niles', 'Youngstown', 'Cortland', 'Girard', 'Champion'] },
    { city: 'Westerville', citySlug: 'westerville', county: 'Franklin County', lat: 40.1262, lng: -82.9291, surroundingCities: ['Columbus', 'Gahanna', 'Worthington', 'New Albany', 'Sunbury'] },
    { city: 'Hilliard', citySlug: 'hilliard', county: 'Franklin County', lat: 40.0334, lng: -83.1582, surroundingCities: ['Columbus', 'Dublin', 'Upper Arlington', 'Grove City', 'Galloway'] },
    { city: 'North Ridgeville', citySlug: 'north-ridgeville', county: 'Lorain County', lat: 41.3892, lng: -82.0193, surroundingCities: ['Elyria', 'Avon', 'North Olmsted', 'Olmsted Falls', 'Lorain'] },
    { city: 'Upper Arlington', citySlug: 'upper-arlington', county: 'Franklin County', lat: 40.0265, lng: -83.0621, surroundingCities: ['Columbus', 'Hilliard', 'Dublin', 'Grandview Heights', 'Worthington'] },
    { city: 'Marion', citySlug: 'marion', county: 'Marion County', lat: 40.5887, lng: -83.1286, surroundingCities: ['Delaware', 'Bucyrus', 'Mount Gilead', 'Kenton', 'Marysville'] },
    { city: 'Mason', citySlug: 'mason', county: 'Warren County', lat: 39.3600, lng: -84.3099, surroundingCities: ['West Chester', 'Lebanon', 'Loveland', 'Fairfield', 'Springboro'] },
    { city: 'Gahanna', citySlug: 'gahanna', county: 'Franklin County', lat: 40.0192, lng: -82.8796, surroundingCities: ['Columbus', 'Westerville', 'Reynoldsburg', 'New Albany', 'Whitehall'] },
    { city: 'Brunswick', citySlug: 'brunswick', county: 'Medina County', lat: 41.2381, lng: -81.8418, surroundingCities: ['Medina', 'Strongsville', 'North Royalton', 'Hinckley', 'Berea'] },
    { city: 'Lima', citySlug: 'lima', county: 'Allen County', lat: 40.7426, lng: -84.1052, surroundingCities: ['Findlay', 'Wapakoneta', 'Delphos', 'Bluffton', 'Ottawa'] },
    { city: 'Fairborn', citySlug: 'fairborn', county: 'Greene County', lat: 39.8209, lng: -84.0194, surroundingCities: ['Dayton', 'Beavercreek', 'Huber Heights', 'Xenia', 'Riverside'] },
    { city: 'Stow', citySlug: 'stow', county: 'Summit County', lat: 41.1595, lng: -81.4404, surroundingCities: ['Cuyahoga Falls', 'Kent', 'Munroe Falls', 'Hudson', 'Tallmadge'] },
    { city: 'Westlake', citySlug: 'westlake', county: 'Cuyahoga County', lat: 41.4553, lng: -81.9179, surroundingCities: ['Rocky River', 'Bay Village', 'North Olmsted', 'Avon', 'Lakewood'] },
    { city: 'Massillon', citySlug: 'massillon', county: 'Stark County', lat: 40.7967, lng: -81.5215, surroundingCities: ['Canton', 'North Canton', 'Navarre', 'Orrville', 'Wooster'] },
    { city: 'North Olmsted', citySlug: 'north-olmsted', county: 'Cuyahoga County', lat: 41.4159, lng: -81.9232, surroundingCities: ['Westlake', 'Olmsted Falls', 'North Ridgeville', 'Fairview Park', 'Berea'] },
    { city: 'North Royalton', citySlug: 'north-royalton', county: 'Cuyahoga County', lat: 41.3137, lng: -81.7246, surroundingCities: ['Strongsville', 'Broadview Heights', 'Parma', 'Brecksville', 'Brunswick'] },
    { city: 'Bowling Green', citySlug: 'bowling-green', county: 'Wood County', lat: 41.3748, lng: -83.6513, surroundingCities: ['Perrysburg', 'Toledo', 'Findlay', 'Fostoria', 'Maumee'] },
    { city: 'Kent', citySlug: 'kent', county: 'Portage County', lat: 41.1537, lng: -81.3579, surroundingCities: ['Stow', 'Ravenna', 'Cuyahoga Falls', 'Tallmadge', 'Munroe Falls'] },
    { city: 'Wooster', citySlug: 'wooster', county: 'Wayne County', lat: 40.8051, lng: -81.9351, surroundingCities: ['Orrville', 'Massillon', 'Medina', 'Ashland', 'Rittman'] },
    { city: 'Medina', citySlug: 'medina', county: 'Medina County', lat: 41.1384, lng: -81.8635, surroundingCities: ['Brunswick', 'Wadsworth', 'Wooster', 'Strongsville', 'Hinckley'] },
  ],
  missouri: [
    { city: 'Kansas City', citySlug: 'kansas-city', county: 'Jackson County', lat: 39.0997, lng: -94.5786, surroundingCities: ['Independence', "Lee's Summit", 'Gladstone', 'North Kansas City'] },
    { city: 'St. Louis', citySlug: 'st-louis', county: 'St. Louis City', lat: 38.6270, lng: -90.1994, surroundingCities: ['Clayton', 'Maplewood', 'University City', 'Brentwood'] },
    { city: 'Springfield', citySlug: 'springfield', county: 'Greene County', lat: 37.2090, lng: -93.2923, surroundingCities: ['Nixa', 'Ozark', 'Republic', 'Battlefield'] },
    { city: 'Columbia', citySlug: 'columbia', county: 'Boone County', lat: 38.9517, lng: -92.3341, surroundingCities: ['Ashland', 'Centralia', 'Fulton', 'Boonville'] },
    { city: 'Independence', citySlug: 'independence', county: 'Jackson County', lat: 39.0911, lng: -94.4155, surroundingCities: ['Kansas City', 'Blue Springs', 'Sugar Creek', 'Raytown'] },
    { city: "Lee's Summit", citySlug: 'lees-summit', county: 'Jackson County', lat: 38.9108, lng: -94.3822, surroundingCities: ['Blue Springs', 'Raymore', 'Grandview', 'Lone Jack'] },
    { city: "O'Fallon", citySlug: 'ofallon', county: 'St. Charles County', lat: 38.8106, lng: -90.6998, surroundingCities: ['St. Charles', 'St. Peters', 'Wentzville', 'Lake Saint Louis'] },
    { city: 'St. Joseph', citySlug: 'st-joseph', county: 'Buchanan County', lat: 39.7686, lng: -94.8466, surroundingCities: ['Savannah', 'Wathena', 'Country Club Village', 'Agency'] },
    { city: 'St. Charles', citySlug: 'st-charles', county: 'St. Charles County', lat: 38.7881, lng: -90.4974, surroundingCities: ['St. Peters', "O'Fallon", 'Cottleville', 'Bridgeton'] },
    { city: 'Blue Springs', citySlug: 'blue-springs', county: 'Jackson County', lat: 39.0169, lng: -94.2816, surroundingCities: ['Independence', "Lee's Summit", 'Grain Valley', 'Oak Grove'] },
    { city: 'St. Peters', citySlug: 'st-peters', county: 'St. Charles County', lat: 38.7875, lng: -90.6298, surroundingCities: ['St. Charles', "O'Fallon", 'Cottleville', 'Dardenne Prairie'] },
    { city: 'Florissant', citySlug: 'florissant', county: 'St. Louis County', lat: 38.7892, lng: -90.3223, surroundingCities: ['Hazelwood', 'Ferguson', 'Black Jack', 'Bridgeton'] },
    { city: 'Joplin', citySlug: 'joplin', county: 'Jasper County', lat: 37.0842, lng: -94.5133, surroundingCities: ['Webb City', 'Carthage', 'Carl Junction', 'Duquesne'] },
    { city: 'Chesterfield', citySlug: 'chesterfield', county: 'St. Louis County', lat: 38.6631, lng: -90.5771, surroundingCities: ['Ballwin', 'Wildwood', 'Town and Country', 'Ellisville'] },
    { city: 'Jefferson City', citySlug: 'jefferson-city', county: 'Cole County', lat: 38.5767, lng: -92.1735, surroundingCities: ['Holts Summit', 'Wardsville', 'St. Martins', 'Taos'] },
    { city: 'Cape Girardeau', citySlug: 'cape-girardeau', county: 'Cape Girardeau County', lat: 37.3059, lng: -89.5181, surroundingCities: ['Jackson', 'Scott City', 'Gordonville', 'Chaffee'] },
    { city: 'Wildwood', citySlug: 'wildwood', county: 'St. Louis County', lat: 38.5828, lng: -90.6629, surroundingCities: ['Ballwin', 'Chesterfield', 'Ellisville', 'Eureka'] },
    { city: 'University City', citySlug: 'university-city', county: 'St. Louis County', lat: 38.6657, lng: -90.3315, surroundingCities: ['Clayton', 'Olivette', 'St. Louis', 'Overland'] },
    { city: 'Ballwin', citySlug: 'ballwin', county: 'St. Louis County', lat: 38.5950, lng: -90.5462, surroundingCities: ['Ellisville', 'Manchester', 'Chesterfield', 'Wildwood'] },
    { city: 'Wentzville', citySlug: 'wentzville', county: 'St. Charles County', lat: 38.8114, lng: -90.8529, surroundingCities: ['Lake Saint Louis', "O'Fallon", 'Foristell', 'Flint Hill'] },
    { city: 'Raytown', citySlug: 'raytown', county: 'Jackson County', lat: 39.0086, lng: -94.4636, surroundingCities: ['Kansas City', 'Independence', 'Grandview', "Lee's Summit"] },
    { city: 'Liberty', citySlug: 'liberty', county: 'Clay County', lat: 39.2461, lng: -94.4191, surroundingCities: ['Kansas City', 'Gladstone', 'Kearney', 'Pleasant Valley'] },
    { city: 'Kirkwood', citySlug: 'kirkwood', county: 'St. Louis County', lat: 38.5834, lng: -90.4068, surroundingCities: ['Webster Groves', 'Des Peres', 'Sunset Hills', 'Glendale'] },
    { city: 'Nixa', citySlug: 'nixa', county: 'Christian County', lat: 37.0431, lng: -93.2944, surroundingCities: ['Ozark', 'Springfield', 'Republic', 'Battlefield'] },
    { city: 'Maryland Heights', citySlug: 'maryland-heights', county: 'St. Louis County', lat: 38.7131, lng: -90.4298, surroundingCities: ['Bridgeton', 'Creve Coeur', 'Overland', 'St. Ann'] },
    { city: 'Hazelwood', citySlug: 'hazelwood', county: 'St. Louis County', lat: 38.7794, lng: -90.3564, surroundingCities: ['Florissant', 'Bridgeton', 'Ferguson', 'Black Jack'] },
    { city: 'Gladstone', citySlug: 'gladstone', county: 'Clay County', lat: 39.2039, lng: -94.5547, surroundingCities: ['Kansas City', 'North Kansas City', 'Liberty', 'Pleasant Valley'] },
    { city: 'Grandview', citySlug: 'grandview', county: 'Jackson County', lat: 38.8858, lng: -94.5330, surroundingCities: ['Kansas City', 'Raytown', 'Belton', "Lee's Summit"] },
    { city: 'Belton', citySlug: 'belton', county: 'Cass County', lat: 38.8120, lng: -94.5319, surroundingCities: ['Raymore', 'Grandview', 'Kansas City', 'Peculiar'] },
    { city: 'Webster Groves', citySlug: 'webster-groves', county: 'St. Louis County', lat: 38.5926, lng: -90.3573, surroundingCities: ['Kirkwood', 'Maplewood', 'Glendale', 'Shrewsbury'] },
    { city: 'Sedalia', citySlug: 'sedalia', county: 'Pettis County', lat: 38.7045, lng: -93.2283, surroundingCities: ['Warrensburg', 'Marshall', 'Knob Noster', 'Smithton'] },
    { city: 'Ferguson', citySlug: 'ferguson', county: 'St. Louis County', lat: 38.7442, lng: -90.3054, surroundingCities: ['Florissant', 'Hazelwood', 'Berkeley', 'Dellwood'] },
    { city: 'Raymore', citySlug: 'raymore', county: 'Cass County', lat: 38.8019, lng: -94.4530, surroundingCities: ['Belton', "Lee's Summit", 'Peculiar', 'Grandview'] },
    { city: 'Ozark', citySlug: 'ozark', county: 'Christian County', lat: 37.0209, lng: -93.2060, surroundingCities: ['Nixa', 'Springfield', 'Sparta', 'Rogersville'] },
    { city: 'Arnold', citySlug: 'arnold', county: 'Jefferson County', lat: 38.4328, lng: -90.3779, surroundingCities: ['Imperial', 'Fenton', 'Oakville', 'Barnhart'] },
    { city: 'Rolla', citySlug: 'rolla', county: 'Phelps County', lat: 37.9514, lng: -91.7713, surroundingCities: ['St. James', 'Newburg', 'Salem', 'Waynesville'] },
    { city: 'Warrensburg', citySlug: 'warrensburg', county: 'Johnson County', lat: 38.7628, lng: -93.7360, surroundingCities: ['Knob Noster', 'Sedalia', 'Holden', 'Centerview'] },
    { city: 'Republic', citySlug: 'republic', county: 'Greene County', lat: 37.1201, lng: -93.4796, surroundingCities: ['Springfield', 'Nixa', 'Battlefield', 'Willard'] },
    { city: 'Kennett', citySlug: 'kennett', county: 'Dunklin County', lat: 36.2362, lng: -90.0557, surroundingCities: ['Malden', 'Hayti', 'Caruthersville', 'Senath'] },
    { city: 'Farmington', citySlug: 'farmington', county: 'St. Francois County', lat: 37.7809, lng: -90.4218, surroundingCities: ['Park Hills', 'Bonne Terre', 'Desloge', 'Fredericktown'] },
    { city: 'Poplar Bluff', citySlug: 'poplar-bluff', county: 'Butler County', lat: 36.7570, lng: -90.3929, surroundingCities: ['Dexter', 'Qulin', 'Naylor', 'Fisk'] },
    { city: 'Hannibal', citySlug: 'hannibal', county: 'Marion County', lat: 39.7084, lng: -91.3585, surroundingCities: ['Palmyra', 'New London', 'Monroe City', 'Louisiana'] },
  ],
  kentucky: [
    { city: 'Louisville', citySlug: 'louisville', county: 'Jefferson County', lat: 38.2527, lng: -85.7585, surroundingCities: ['Jeffersontown', 'St. Matthews', 'Shively', 'New Albany', 'Jeffersonville'] },
    { city: 'Lexington', citySlug: 'lexington', county: 'Fayette County', lat: 38.0406, lng: -84.5037, surroundingCities: ['Nicholasville', 'Georgetown', 'Richmond', 'Versailles', 'Winchester'] },
    { city: 'Bowling Green', citySlug: 'bowling-green', county: 'Warren County', lat: 36.9685, lng: -86.4808, surroundingCities: ['Oakland', 'Smiths Grove', 'Plum Springs', 'Franklin'] },
    { city: 'Owensboro', citySlug: 'owensboro', county: 'Daviess County', lat: 37.7719, lng: -87.1112, surroundingCities: ['Whitesville', 'Philpot', 'Maceo', 'Hawesville'] },
    { city: 'Covington', citySlug: 'covington', county: 'Kenton County', lat: 39.0837, lng: -84.5086, surroundingCities: ['Newport', 'Fort Mitchell', 'Erlanger', 'Cincinnati', 'Bellevue'] },
    { city: 'Georgetown', citySlug: 'georgetown', county: 'Scott County', lat: 38.2098, lng: -84.5588, surroundingCities: ['Lexington', 'Sadieville', 'Stamping Ground', 'Midway'] },
    { city: 'Richmond', citySlug: 'richmond', county: 'Madison County', lat: 37.7479, lng: -84.2947, surroundingCities: ['Berea', 'Winchester', 'Lexington', 'Nicholasville'] },
    { city: 'Florence', citySlug: 'florence', county: 'Boone County', lat: 38.9989, lng: -84.6266, surroundingCities: ['Erlanger', 'Union', 'Independence', 'Edgewood', 'Covington'] },
    { city: 'Elizabethtown', citySlug: 'elizabethtown', county: 'Hardin County', lat: 37.6936, lng: -85.8591, surroundingCities: ['Radcliff', 'Vine Grove', 'Cecilia', 'Sonora'] },
    { city: 'Hopkinsville', citySlug: 'hopkinsville', county: 'Christian County', lat: 36.8656, lng: -87.4886, surroundingCities: ['Oak Grove', 'Pembroke', 'Crofton', 'Cadiz'] },
    { city: 'Nicholasville', citySlug: 'nicholasville', county: 'Jessamine County', lat: 37.8806, lng: -84.5730, surroundingCities: ['Lexington', 'Wilmore', 'Versailles', 'Richmond'] },
    { city: 'Frankfort', citySlug: 'frankfort', county: 'Franklin County', lat: 38.2009, lng: -84.8733, surroundingCities: ['Versailles', 'Lawrenceburg', 'Midway', 'Georgetown'] },
    { city: 'Jeffersontown', citySlug: 'jeffersontown', county: 'Jefferson County', lat: 38.1942, lng: -85.5644, surroundingCities: ['Louisville', 'Middletown', 'Lyndon', 'St. Matthews'] },
    { city: 'Henderson', citySlug: 'henderson', county: 'Henderson County', lat: 37.8362, lng: -87.5900, surroundingCities: ['Evansville', 'Corydon', 'Robards', 'Sebree'] },
    { city: 'Paducah', citySlug: 'paducah', county: 'McCracken County', lat: 37.0834, lng: -88.6000, surroundingCities: ['Lone Oak', 'Reidland', 'Calvert City', 'Metropolis'] },
    { city: 'Radcliff', citySlug: 'radcliff', county: 'Hardin County', lat: 37.8403, lng: -85.9491, surroundingCities: ['Elizabethtown', 'Vine Grove', 'Fort Knox', 'Brandenburg'] },
    { city: 'Ashland', citySlug: 'ashland', county: 'Boyd County', lat: 38.4784, lng: -82.6379, surroundingCities: ['Catlettsburg', 'Flatwoods', 'Russell', 'Huntington'] },
    { city: 'Madisonville', citySlug: 'madisonville', county: 'Hopkins County', lat: 37.3281, lng: -87.4989, surroundingCities: ['Earlington', 'Nortonville', 'Dawson Springs', 'Hanson'] },
    { city: 'Erlanger', citySlug: 'erlanger', county: 'Kenton County', lat: 39.0167, lng: -84.6008, surroundingCities: ['Florence', 'Covington', 'Fort Mitchell', 'Edgewood', 'Elsmere'] },
    { city: 'Winchester', citySlug: 'winchester', county: 'Clark County', lat: 37.9904, lng: -84.1791, surroundingCities: ['Lexington', 'Mount Sterling', 'Richmond', 'Paris'] },
    { city: 'Murray', citySlug: 'murray', county: 'Calloway County', lat: 36.6103, lng: -88.3148, surroundingCities: ['Mayfield', 'Benton', 'Hazel', 'Paducah'] },
    { city: 'St. Matthews', citySlug: 'st-matthews', county: 'Jefferson County', lat: 38.2526, lng: -85.6535, surroundingCities: ['Louisville', 'Lyndon', 'Jeffersontown', 'Shively'] },
    { city: 'Fort Thomas', citySlug: 'fort-thomas', county: 'Campbell County', lat: 39.0751, lng: -84.4472, surroundingCities: ['Newport', 'Bellevue', 'Cold Spring', 'Covington'] },
    { city: 'Danville', citySlug: 'danville', county: 'Boyle County', lat: 37.6456, lng: -84.7722, surroundingCities: ['Harrodsburg', 'Stanford', 'Junction City', 'Perryville'] },
    { city: 'Shelbyville', citySlug: 'shelbyville', county: 'Shelby County', lat: 38.2120, lng: -85.2236, surroundingCities: ['Simpsonville', 'La Grange', 'Frankfort', 'Taylorsville'] },
    { city: 'Mount Washington', citySlug: 'mount-washington', county: 'Bullitt County', lat: 37.9476, lng: -85.5447, surroundingCities: ['Shepherdsville', 'Hillview', 'Taylorsville', 'Louisville'] },
    { city: 'Shively', citySlug: 'shively', county: 'Jefferson County', lat: 38.2003, lng: -85.8222, surroundingCities: ['Louisville', 'St. Matthews', 'Pleasure Ridge Park', 'Valley Station'] },
    { city: 'Newport', citySlug: 'newport', county: 'Campbell County', lat: 39.0915, lng: -84.4958, surroundingCities: ['Covington', 'Bellevue', 'Fort Thomas', 'Cincinnati'] },
    { city: 'Berea', citySlug: 'berea', county: 'Madison County', lat: 37.5687, lng: -84.2963, surroundingCities: ['Richmond', 'Mount Vernon', 'Paint Lick', 'Lancaster'] },
    { city: 'Lyndon', citySlug: 'lyndon', county: 'Jefferson County', lat: 38.2570, lng: -85.5894, surroundingCities: ['St. Matthews', 'Jeffersontown', 'Middletown', 'Louisville'] },
    { city: 'Somerset', citySlug: 'somerset', county: 'Pulaski County', lat: 37.0920, lng: -84.6041, surroundingCities: ['Burnside', 'Science Hill', 'Ferguson', 'Eubank'] },
    { city: 'Campbellsville', citySlug: 'campbellsville', county: 'Taylor County', lat: 37.3434, lng: -85.3419, surroundingCities: ['Greensburg', 'Lebanon', 'Columbia', 'Hodgenville'] },
    { city: 'Lawrenceburg', citySlug: 'lawrenceburg', county: 'Anderson County', lat: 38.0373, lng: -84.8966, surroundingCities: ['Frankfort', 'Versailles', 'Harrodsburg', 'Lexington'] },
    { city: 'Middlesboro', citySlug: 'middlesboro', county: 'Bell County', lat: 36.6084, lng: -83.7163, surroundingCities: ['Pineville', 'Harlan', 'Cumberland Gap', 'Barbourville'] },
    { city: 'Maysville', citySlug: 'maysville', county: 'Mason County', lat: 38.6412, lng: -83.7443, surroundingCities: ['Flemingsburg', 'Aberdeen', 'Augusta', 'Mount Olivet'] },
    { city: 'Glasgow', citySlug: 'glasgow', county: 'Barren County', lat: 36.9959, lng: -85.9119, surroundingCities: ['Cave City', 'Horse Cave', 'Park City', 'Bowling Green'] },
    { city: 'Harrodsburg', citySlug: 'harrodsburg', county: 'Mercer County', lat: 37.7625, lng: -84.8430, surroundingCities: ['Danville', 'Lawrenceburg', 'Wilmore', 'Lancaster'] },
  ],
  pennsylvania: [
    { city: 'Philadelphia', citySlug: 'philadelphia', county: 'Philadelphia County', lat: 39.9526, lng: -75.1652, surroundingCities: ['King of Prussia', 'Norristown', 'Upper Darby', 'Media', 'Cheltenham'] },
    { city: 'Pittsburgh', citySlug: 'pittsburgh', county: 'Allegheny County', lat: 40.4406, lng: -79.9959, surroundingCities: ['Mount Lebanon', 'Bethel Park', 'Penn Hills', 'McKeesport', 'Wilkinsburg'] },
    { city: 'Allentown', citySlug: 'allentown', county: 'Lehigh County', lat: 40.6084, lng: -75.4902, surroundingCities: ['Bethlehem', 'Easton', 'Whitehall', 'Emmaus', 'Catasauqua'] },
    { city: 'Reading', citySlug: 'reading', county: 'Berks County', lat: 40.3356, lng: -75.9269, surroundingCities: ['Wyomissing', 'West Reading', 'Shillington', 'Sinking Spring', 'Laureldale'] },
    { city: 'Erie', citySlug: 'erie', county: 'Erie County', lat: 42.1292, lng: -80.0851, surroundingCities: ['Millcreek', 'Harborcreek', 'Wesleyville', 'Lawrence Park', 'North East'] },
    { city: 'Upper Darby', citySlug: 'upper-darby', county: 'Delaware County', lat: 39.9590, lng: -75.2590, surroundingCities: ['Philadelphia', 'Drexel Hill', 'Lansdowne', 'Havertown', 'Clifton Heights'] },
    { city: 'Scranton', citySlug: 'scranton', county: 'Lackawanna County', lat: 41.4090, lng: -75.6624, surroundingCities: ['Dunmore', 'Dickson City', 'Taylor', 'Old Forge', 'Moosic'] },
    { city: 'Bethlehem', citySlug: 'bethlehem', county: 'Northampton County', lat: 40.6259, lng: -75.3705, surroundingCities: ['Allentown', 'Easton', 'Freemansburg', 'Hellertown', 'Nazareth'] },
    { city: 'Lancaster', citySlug: 'lancaster', county: 'Lancaster County', lat: 40.0379, lng: -76.3055, surroundingCities: ['Lititz', 'Manheim', 'Columbia', 'Ephrata', 'Millersville'] },
    { city: 'Harrisburg', citySlug: 'harrisburg', county: 'Dauphin County', lat: 40.2732, lng: -76.8867, surroundingCities: ['Camp Hill', 'Mechanicsburg', 'Hershey', 'Hummelstown', 'Steelton'] },
    { city: 'Levittown', citySlug: 'levittown', county: 'Bucks County', lat: 40.1551, lng: -74.8288, surroundingCities: ['Bristol', 'Fairless Hills', 'Morrisville', 'Langhorne', 'Tullytown'] },
    { city: 'York', citySlug: 'york', county: 'York County', lat: 39.9626, lng: -76.7277, surroundingCities: ['Hanover', 'Red Lion', 'Dover', 'Spring Garden', 'West York'] },
    { city: 'Altoona', citySlug: 'altoona', county: 'Blair County', lat: 40.5187, lng: -78.3947, surroundingCities: ['Hollidaysburg', 'Duncansville', 'Bellwood', 'Tyrone', 'Roaring Spring'] },
    { city: 'Wilkes-Barre', citySlug: 'wilkes-barre', county: 'Luzerne County', lat: 41.2459, lng: -75.8813, surroundingCities: ['Kingston', 'Pittston', 'Hazleton', 'Nanticoke', 'Plymouth'] },
    { city: 'Chester', citySlug: 'chester', county: 'Delaware County', lat: 39.8496, lng: -75.3557, surroundingCities: ['Media', 'Brookhaven', 'Marcus Hook', 'Ridley Park', 'Aston'] },
    { city: 'Williamsport', citySlug: 'williamsport', county: 'Lycoming County', lat: 41.2412, lng: -77.0011, surroundingCities: ['South Williamsport', 'Montoursville', 'Loyalsock', 'Jersey Shore', 'Muncy'] },
    { city: 'Easton', citySlug: 'easton', county: 'Northampton County', lat: 40.6884, lng: -75.2207, surroundingCities: ['Bethlehem', 'Phillipsburg', 'Wilson', 'Nazareth', 'Palmer'] },
    { city: 'Lebanon', citySlug: 'lebanon', county: 'Lebanon County', lat: 40.3409, lng: -76.4113, surroundingCities: ['Annville', 'Palmyra', 'Cleona', 'Myerstown', 'Jonestown'] },
    { city: 'Hazleton', citySlug: 'hazleton', county: 'Luzerne County', lat: 40.9584, lng: -75.9746, surroundingCities: ['West Hazleton', 'Freeland', 'McAdoo', 'Conyngham', 'Drums'] },
    { city: 'New Castle', citySlug: 'new-castle', county: 'Lawrence County', lat: 40.9959, lng: -80.3470, surroundingCities: ['Ellwood City', 'Neshannock', 'Mahoningtown', 'Sharon', 'Hermitage'] },
    { city: 'Johnstown', citySlug: 'johnstown', county: 'Cambria County', lat: 40.3267, lng: -78.9220, surroundingCities: ['Westmont', 'Richland', 'Conemaugh', 'Ebensburg', 'Windber'] },
    { city: 'McKeesport', citySlug: 'mckeesport', county: 'Allegheny County', lat: 40.3473, lng: -79.8645, surroundingCities: ['White Oak', 'Duquesne', 'Glassport', 'Clairton', 'West Mifflin'] },
    { city: 'Norristown', citySlug: 'norristown', county: 'Montgomery County', lat: 40.1215, lng: -75.3399, surroundingCities: ['King of Prussia', 'Bridgeport', 'Plymouth Meeting', 'Conshohocken', 'Audubon'] },
    { city: 'State College', citySlug: 'state-college', county: 'Centre County', lat: 40.7934, lng: -77.8600, surroundingCities: ['Bellefonte', 'Boalsburg', 'Pleasant Gap', 'Port Matilda', 'Lemont'] },
    { city: 'King of Prussia', citySlug: 'king-of-prussia', county: 'Montgomery County', lat: 40.0890, lng: -75.3960, surroundingCities: ['Norristown', 'Wayne', 'Bridgeport', 'Conshohocken', 'Valley Forge'] },
    { city: 'Wilkinsburg', citySlug: 'wilkinsburg', county: 'Allegheny County', lat: 40.4445, lng: -79.8772, surroundingCities: ['Pittsburgh', 'Penn Hills', 'Edgewood', 'Swissvale', 'Forest Hills'] },
    { city: 'West Chester', citySlug: 'west-chester', county: 'Chester County', lat: 39.9607, lng: -75.6055, surroundingCities: ['Downingtown', 'Exton', 'Coatesville', 'Kennett Square', 'Malvern'] },
    { city: 'Pottstown', citySlug: 'pottstown', county: 'Montgomery County', lat: 40.2454, lng: -75.6496, surroundingCities: ['Phoenixville', 'Boyertown', 'Royersford', 'Limerick', 'Stowe'] },
    { city: 'Bethel Park', citySlug: 'bethel-park', county: 'Allegheny County', lat: 40.3270, lng: -80.0373, surroundingCities: ['Mount Lebanon', 'Upper St. Clair', 'South Park', 'Pittsburgh', 'Castle Shannon'] },
    { city: 'Monroeville', citySlug: 'monroeville', county: 'Allegheny County', lat: 40.4212, lng: -79.7881, surroundingCities: ['Penn Hills', 'Plum', 'Wilkinsburg', 'Murrysville', 'Pitcairn'] },
    { city: 'Plum', citySlug: 'plum', county: 'Allegheny County', lat: 40.5009, lng: -79.7464, surroundingCities: ['Monroeville', 'Penn Hills', 'New Kensington', 'Murrysville', 'Verona'] },
    { city: 'Drexel Hill', citySlug: 'drexel-hill', county: 'Delaware County', lat: 39.9479, lng: -75.2932, surroundingCities: ['Upper Darby', 'Havertown', 'Springfield', 'Clifton Heights', 'Lansdowne'] },
    { city: 'Mount Lebanon', citySlug: 'mount-lebanon', county: 'Allegheny County', lat: 40.3759, lng: -80.0495, surroundingCities: ['Pittsburgh', 'Bethel Park', 'Castle Shannon', 'Dormont', 'Upper St. Clair'] },
    { city: 'Penn Hills', citySlug: 'penn-hills', county: 'Allegheny County', lat: 40.4767, lng: -79.8281, surroundingCities: ['Pittsburgh', 'Monroeville', 'Verona', 'Wilkinsburg', 'Plum'] },
    { city: 'Phoenixville', citySlug: 'phoenixville', county: 'Chester County', lat: 40.1301, lng: -75.5149, surroundingCities: ['Pottstown', 'Collegeville', 'Royersford', 'Spring City', 'Valley Forge'] },
    { city: 'Hermitage', citySlug: 'hermitage', county: 'Mercer County', lat: 41.2334, lng: -80.4495, surroundingCities: ['Sharon', 'Farrell', 'Greenville', 'Mercer', 'Wheatland'] },
    { city: 'Carlisle', citySlug: 'carlisle', county: 'Cumberland County', lat: 40.2009, lng: -77.2003, surroundingCities: ['Mechanicsburg', 'Camp Hill', 'Shippensburg', 'Newville', 'Boiling Springs'] },
    { city: 'Hanover', citySlug: 'hanover', county: 'York County', lat: 39.8007, lng: -76.9830, surroundingCities: ['York', 'Spring Grove', 'McSherrystown', 'New Oxford', 'Littlestown'] },
    { city: 'Chambersburg', citySlug: 'chambersburg', county: 'Franklin County', lat: 39.9376, lng: -77.6611, surroundingCities: ['Shippensburg', 'Waynesboro', 'Greencastle', 'Mercersburg', 'Fayetteville'] },
    { city: 'Bloomsburg', citySlug: 'bloomsburg', county: 'Columbia County', lat: 41.0037, lng: -76.4549, surroundingCities: ['Berwick', 'Danville', 'Catawissa', 'Mifflinville', 'Espy'] },
    { city: 'Indiana', citySlug: 'indiana', county: 'Indiana County', lat: 40.6215, lng: -79.1525, surroundingCities: ['Homer City', 'Blairsville', 'Clymer', 'Punxsutawney', 'Saltsburg'] },
    { city: 'Greensburg', citySlug: 'greensburg', county: 'Westmoreland County', lat: 40.3015, lng: -79.5389, surroundingCities: ['Jeannette', 'Latrobe', 'Irwin', 'Murrysville', 'Hempfield'] },
    { city: 'Butler', citySlug: 'butler', county: 'Butler County', lat: 40.8612, lng: -79.8953, surroundingCities: ['Cranberry Township', 'Saxonburg', 'Zelienople', 'Mars', 'Slippery Rock'] },
    { city: 'Pottsville', citySlug: 'pottsville', county: 'Schuylkill County', lat: 40.6856, lng: -76.1955, surroundingCities: ['Saint Clair', 'Minersville', 'Schuylkill Haven', 'Frackville', 'Orwigsburg'] },
    { city: 'Sunbury', citySlug: 'sunbury', county: 'Northumberland County', lat: 40.8623, lng: -76.7944, surroundingCities: ['Shamokin', 'Selinsgrove', 'Northumberland', 'Milton', 'Lewisburg'] },
    { city: 'Uniontown', citySlug: 'uniontown', county: 'Fayette County', lat: 39.9001, lng: -79.7164, surroundingCities: ['Connellsville', 'Brownsville', 'Masontown', 'Smithfield', 'Hopwood'] },
    { city: 'Meadville', citySlug: 'meadville', county: 'Crawford County', lat: 41.6412, lng: -80.1514, surroundingCities: ['Cambridge Springs', 'Saegertown', 'Conneaut Lake', 'Titusville', 'Linesville'] },
    { city: 'Lock Haven', citySlug: 'lock-haven', county: 'Clinton County', lat: 41.1370, lng: -77.4469, surroundingCities: ['Mill Hall', 'Jersey Shore', 'Williamsport', 'Avis', 'Flemington'] },
  ],
  maryland: [
    { city: 'Baltimore', citySlug: 'baltimore', county: 'Baltimore City', lat: 39.2904, lng: -76.6122, surroundingCities: ['Towson', 'Dundalk', 'Ellicott City', 'Glen Burnie', 'Columbia'] },
    { city: 'Columbia', citySlug: 'columbia', county: 'Howard', lat: 39.2037, lng: -76.8610, surroundingCities: ['Ellicott City', 'Laurel', 'Elkridge', 'Clarksville'] },
    { city: 'Germantown', citySlug: 'germantown', county: 'Montgomery', lat: 39.1732, lng: -77.2717, surroundingCities: ['Gaithersburg', 'Rockville', 'Clarksburg', 'Damascus'] },
    { city: 'Waldorf', citySlug: 'waldorf', county: 'Charles', lat: 38.6246, lng: -76.9391, surroundingCities: ['La Plata', 'Brandywine', 'Accokeek', 'White Plains'] },
    { city: 'Silver Spring', citySlug: 'silver-spring', county: 'Montgomery', lat: 38.9907, lng: -77.0261, surroundingCities: ['Takoma Park', 'Wheaton', 'Bethesda', 'Hyattsville'] },
    { city: 'Glen Burnie', citySlug: 'glen-burnie', county: 'Anne Arundel', lat: 39.1626, lng: -76.6247, surroundingCities: ['Severn', 'Pasadena', 'Linthicum', 'Brooklyn Park'] },
    { city: 'Frederick', citySlug: 'frederick', county: 'Frederick', lat: 39.4143, lng: -77.4105, surroundingCities: ['Urbana', 'Walkersville', 'Middletown', 'Mount Airy'] },
    { city: 'Ellicott City', citySlug: 'ellicott-city', county: 'Howard', lat: 39.2673, lng: -76.7983, surroundingCities: ['Columbia', 'Catonsville', 'Elkridge', 'Baltimore'] },
    { city: 'Gaithersburg', citySlug: 'gaithersburg', county: 'Montgomery', lat: 39.1434, lng: -77.2014, surroundingCities: ['Rockville', 'Germantown', 'Montgomery Village', 'Potomac'] },
    { city: 'Rockville', citySlug: 'rockville', county: 'Montgomery', lat: 39.0840, lng: -77.1528, surroundingCities: ['Gaithersburg', 'Bethesda', 'Potomac', 'North Bethesda'] },
    { city: 'Dundalk', citySlug: 'dundalk', county: 'Baltimore', lat: 39.2509, lng: -76.5205, surroundingCities: ['Baltimore', 'Essex', 'Edgemere', 'Rosedale'] },
    { city: 'Bowie', citySlug: 'bowie', county: "Prince George's", lat: 38.9427, lng: -76.7300, surroundingCities: ['Crofton', 'Laurel', 'Upper Marlboro', 'Mitchellville'] },
    { city: 'Towson', citySlug: 'towson', county: 'Baltimore', lat: 39.4015, lng: -76.6019, surroundingCities: ['Baltimore', 'Lutherville', 'Parkville', 'Pikesville'] },
    { city: 'Aspen Hill', citySlug: 'aspen-hill', county: 'Montgomery', lat: 39.0956, lng: -77.1053, surroundingCities: ['Wheaton', 'Rockville', 'Silver Spring', 'Olney'] },
    { city: 'Bethesda', citySlug: 'bethesda', county: 'Montgomery', lat: 38.9847, lng: -77.0947, surroundingCities: ['Chevy Chase', 'Rockville', 'Potomac', 'North Bethesda'] },
    { city: 'Wheaton', citySlug: 'wheaton', county: 'Montgomery', lat: 39.0376, lng: -77.0527, surroundingCities: ['Silver Spring', 'Aspen Hill', 'Kensington', 'Rockville'] },
    { city: 'Severn', citySlug: 'severn', county: 'Anne Arundel', lat: 39.1373, lng: -76.6983, surroundingCities: ['Glen Burnie', 'Odenton', 'Severna Park', 'Hanover'] },
    { city: 'Hagerstown', citySlug: 'hagerstown', county: 'Washington', lat: 39.6418, lng: -77.7200, surroundingCities: ['Williamsport', 'Funkstown', 'Smithsburg', 'Boonsboro'] },
    { city: 'Annapolis', citySlug: 'annapolis', county: 'Anne Arundel', lat: 38.9784, lng: -76.4922, surroundingCities: ['Severna Park', 'Edgewater', 'Arnold', 'Parole'] },
    { city: 'Bel Air South', citySlug: 'bel-air-south', county: 'Harford', lat: 39.5086, lng: -76.3289, surroundingCities: ['Bel Air', 'Abingdon', 'Fallston', 'Forest Hill'] },
    { city: 'Odenton', citySlug: 'odenton', county: 'Anne Arundel', lat: 39.0840, lng: -76.7000, surroundingCities: ['Severn', 'Crofton', 'Gambrills', 'Fort Meade'] },
    { city: 'Bel Air North', citySlug: 'bel-air-north', county: 'Harford', lat: 39.5621, lng: -76.3697, surroundingCities: ['Bel Air', 'Forest Hill', 'Fallston', 'Jarrettsville'] },
    { city: 'Severna Park', citySlug: 'severna-park', county: 'Anne Arundel', lat: 39.0707, lng: -76.5455, surroundingCities: ['Arnold', 'Pasadena', 'Annapolis', 'Millersville'] },
    { city: 'Essex', citySlug: 'essex', county: 'Baltimore', lat: 39.3093, lng: -76.4750, surroundingCities: ['Dundalk', 'Rosedale', 'Middle River', 'Baltimore'] },
    { city: 'Salisbury', citySlug: 'salisbury', county: 'Wicomico', lat: 38.3607, lng: -75.5994, surroundingCities: ['Fruitland', 'Delmar', 'Hebron', 'Pittsville'] },
    { city: 'Catonsville', citySlug: 'catonsville', county: 'Baltimore', lat: 39.2720, lng: -76.7319, surroundingCities: ['Ellicott City', 'Arbutus', 'Baltimore', 'Halethorpe'] },
    { city: 'Montgomery Village', citySlug: 'montgomery-village', county: 'Montgomery', lat: 39.1781, lng: -77.1953, surroundingCities: ['Gaithersburg', 'Germantown', 'Rockville', 'Damascus'] },
    { city: 'Eldersburg', citySlug: 'eldersburg', county: 'Carroll', lat: 39.4040, lng: -76.9533, surroundingCities: ['Sykesville', 'Westminster', 'Mount Airy', 'Finksburg'] },
    { city: 'Owings Mills', citySlug: 'owings-mills', county: 'Baltimore', lat: 39.4196, lng: -76.7803, surroundingCities: ['Pikesville', 'Reisterstown', 'Randallstown', 'Towson'] },
    { city: 'Pikesville', citySlug: 'pikesville', county: 'Baltimore', lat: 39.3743, lng: -76.7225, surroundingCities: ['Owings Mills', 'Towson', 'Randallstown', 'Baltimore'] },
    { city: 'Laurel', citySlug: 'laurel', county: "Prince George's", lat: 39.0993, lng: -76.8483, surroundingCities: ['Columbia', 'Bowie', 'Beltsville', 'Burtonsville'] },
    { city: 'College Park', citySlug: 'college-park', county: "Prince George's", lat: 38.9897, lng: -76.9378, surroundingCities: ['Hyattsville', 'Greenbelt', 'Beltsville', 'Riverdale Park'] },
    { city: 'Hyattsville', citySlug: 'hyattsville', county: "Prince George's", lat: 38.9559, lng: -76.9455, surroundingCities: ['College Park', 'Riverdale Park', 'Mount Rainier', 'Silver Spring'] },
    { city: 'Westminster', citySlug: 'westminster', county: 'Carroll', lat: 39.5754, lng: -76.9958, surroundingCities: ['Eldersburg', 'Hampstead', 'Sykesville', 'Taneytown'] },
    { city: 'Elkton', citySlug: 'elkton', county: 'Cecil', lat: 39.6068, lng: -75.8333, surroundingCities: ['North East', 'Newark', 'Perryville', 'Chesapeake City'] },
    { city: 'Greenbelt', citySlug: 'greenbelt', county: "Prince George's", lat: 39.0046, lng: -76.8755, surroundingCities: ['College Park', 'Hyattsville', 'Bowie', 'Laurel'] },
    { city: 'Cumberland', citySlug: 'cumberland', county: 'Allegany', lat: 39.6529, lng: -78.7625, surroundingCities: ['LaVale', 'Cresaptown', 'Frostburg', 'Ridgeley'] },
    { city: 'Easton', citySlug: 'easton', county: 'Talbot', lat: 38.7743, lng: -76.0763, surroundingCities: ['St. Michaels', 'Trappe', 'Cambridge', 'Oxford'] },
  ],
  'west-virginia': [
    { city: 'Charleston', citySlug: 'charleston', county: 'Kanawha County', lat: 38.3498, lng: -81.6326, surroundingCities: ['South Charleston', 'Dunbar', 'St. Albans', 'Nitro'] },
    { city: 'Huntington', citySlug: 'huntington', county: 'Cabell County', lat: 38.4192, lng: -82.4452, surroundingCities: ['Barboursville', 'Kenova', 'Ceredo', 'Milton'] },
    { city: 'Morgantown', citySlug: 'morgantown', county: 'Monongalia County', lat: 39.6295, lng: -79.9559, surroundingCities: ['Westover', 'Star City', 'Granville', 'Cheat Lake'] },
    { city: 'Parkersburg', citySlug: 'parkersburg', county: 'Wood County', lat: 39.2667, lng: -81.5615, surroundingCities: ['Vienna', 'Williamstown', 'Marietta', 'Belpre'] },
    { city: 'Wheeling', citySlug: 'wheeling', county: 'Ohio County', lat: 40.0640, lng: -80.7209, surroundingCities: ['Moundsville', 'Benwood', 'Bethlehem', 'St. Clairsville'] },
    { city: 'Martinsburg', citySlug: 'martinsburg', county: 'Berkeley County', lat: 39.4562, lng: -77.9639, surroundingCities: ['Inwood', 'Hedgesville', 'Spring Mills', 'Falling Waters'] },
    { city: 'Weirton', citySlug: 'weirton', county: 'Hancock County', lat: 40.4189, lng: -80.5895, surroundingCities: ['Follansbee', 'Wellsburg', 'Steubenville', 'Chester'] },
    { city: 'Fairmont', citySlug: 'fairmont', county: 'Marion County', lat: 39.4851, lng: -80.1426, surroundingCities: ['Mannington', 'White Hall', 'Pleasant Valley', 'Grafton'] },
    { city: 'Beckley', citySlug: 'beckley', county: 'Raleigh County', lat: 37.7782, lng: -81.1882, surroundingCities: ['Mabscott', 'Sophia', 'Crab Orchard', 'Oak Hill'] },
    { city: 'Clarksburg', citySlug: 'clarksburg', county: 'Harrison County', lat: 39.2806, lng: -80.3445, surroundingCities: ['Bridgeport', 'Nutter Fort', 'Stonewood', 'Shinnston'] },
    { city: 'South Charleston', citySlug: 'south-charleston', county: 'Kanawha County', lat: 38.3684, lng: -81.6998, surroundingCities: ['Charleston', 'Dunbar', 'St. Albans', 'Nitro'] },
    { city: 'St. Albans', citySlug: 'st-albans', county: 'Kanawha County', lat: 38.3859, lng: -81.8362, surroundingCities: ['Nitro', 'Dunbar', 'South Charleston', 'Cross Lanes'] },
    { city: 'Vienna', citySlug: 'vienna', county: 'Wood County', lat: 39.3270, lng: -81.5485, surroundingCities: ['Parkersburg', 'Williamstown', 'Marietta', 'Belpre'] },
    { city: 'Bluefield', citySlug: 'bluefield', county: 'Mercer County', lat: 37.2698, lng: -81.2223, surroundingCities: ['Princeton', 'Bluewell', 'Bramwell', 'Athens'] },
    { city: 'Bridgeport', citySlug: 'bridgeport', county: 'Harrison County', lat: 39.2862, lng: -80.2570, surroundingCities: ['Clarksburg', 'Nutter Fort', 'Stonewood', 'Shinnston'] },
    { city: 'Oak Hill', citySlug: 'oak-hill', county: 'Fayette County', lat: 37.9718, lng: -81.1485, surroundingCities: ['Fayetteville', 'Beckley', 'Mount Hope', 'Scarbro'] },
    { city: 'Moundsville', citySlug: 'moundsville', county: 'Marshall County', lat: 39.9209, lng: -80.7423, surroundingCities: ['Wheeling', 'Benwood', 'McMechen', 'Glen Dale'] },
    { city: 'Charles Town', citySlug: 'charles-town', county: 'Jefferson County', lat: 39.2890, lng: -77.8597, surroundingCities: ['Ranson', 'Harpers Ferry', 'Shepherdstown', 'Martinsburg'] },
    { city: 'Dunbar', citySlug: 'dunbar', county: 'Kanawha County', lat: 38.3609, lng: -81.7382, surroundingCities: ['Charleston', 'South Charleston', 'St. Albans', 'Nitro'] },
    { city: 'Hurricane', citySlug: 'hurricane', county: 'Putnam County', lat: 38.4337, lng: -82.0271, surroundingCities: ['Teays Valley', 'Nitro', 'Scott Depot', 'Winfield'] },
    { city: 'Nitro', citySlug: 'nitro', county: 'Kanawha County', lat: 38.4112, lng: -81.8443, surroundingCities: ['St. Albans', 'Dunbar', 'Hurricane', 'Cross Lanes'] },
    { city: 'Elkins', citySlug: 'elkins', county: 'Randolph County', lat: 38.9259, lng: -79.8467, surroundingCities: ['Beverly', 'Belington', 'Buckhannon', 'Philippi'] },
    { city: 'Princeton', citySlug: 'princeton', county: 'Mercer County', lat: 37.3668, lng: -81.1026, surroundingCities: ['Bluefield', 'Athens', 'Oakvale', 'Bluewell'] },
    { city: 'Ranson', citySlug: 'ranson', county: 'Jefferson County', lat: 39.2954, lng: -77.8597, surroundingCities: ['Charles Town', 'Martinsburg', 'Harpers Ferry', 'Shepherdstown'] },
    { city: 'Buckhannon', citySlug: 'buckhannon', county: 'Upshur County', lat: 38.9937, lng: -80.2320, surroundingCities: ['Weston', 'Elkins', 'Philippi', 'Clarksburg'] },
    { city: 'Keyser', citySlug: 'keyser', county: 'Mineral County', lat: 39.4404, lng: -78.9736, surroundingCities: ['Cumberland', 'Piedmont', 'Fort Ashby', 'Ridgeley'] },
    { city: 'Barboursville', citySlug: 'barboursville', county: 'Cabell County', lat: 38.4101, lng: -82.2943, surroundingCities: ['Huntington', 'Milton', 'Ona', 'Culloden'] },
    { city: 'Westover', citySlug: 'westover', county: 'Monongalia County', lat: 39.6353, lng: -79.9742, surroundingCities: ['Morgantown', 'Granville', 'Star City', 'Cheat Lake'] },
    { city: 'Point Pleasant', citySlug: 'point-pleasant', county: 'Mason County', lat: 38.8451, lng: -82.1371, surroundingCities: ['Gallipolis', 'Henderson', 'Mason', 'Hartford City'] },
    { city: 'Weston', citySlug: 'weston', county: 'Lewis County', lat: 39.0376, lng: -80.4673, surroundingCities: ['Buckhannon', 'Clarksburg', 'Jane Lew', 'Bridgeport'] },
    { city: 'Lewisburg', citySlug: 'lewisburg', county: 'Greenbrier County', lat: 37.8018, lng: -80.4456, surroundingCities: ['White Sulphur Springs', 'Ronceverte', 'Fairlea', 'Rainelle'] },
  ],
  'south-carolina': [
    { city: 'Charleston', citySlug: 'charleston', county: 'Charleston County', lat: 32.7765, lng: -79.9311, surroundingCities: ['Mount Pleasant', 'North Charleston', 'Summerville', 'Goose Creek'] },
    { city: 'Columbia', citySlug: 'columbia', county: 'Richland County', lat: 34.0007, lng: -81.0348, surroundingCities: ['West Columbia', 'Cayce', 'Forest Acres', 'Lexington', 'St. Andrews'] },
    { city: 'North Charleston', citySlug: 'north-charleston', county: 'Charleston County', lat: 32.8546, lng: -79.9748, surroundingCities: ['Charleston', 'Goose Creek', 'Hanahan', 'Summerville', 'Ladson'] },
    { city: 'Mount Pleasant', citySlug: 'mount-pleasant', county: 'Charleston County', lat: 32.8323, lng: -79.8284, surroundingCities: ['Charleston', 'Isle of Palms', "Sullivan's Island", 'Daniel Island'] },
    { city: 'Rock Hill', citySlug: 'rock-hill', county: 'York County', lat: 34.9249, lng: -81.0251, surroundingCities: ['Fort Mill', 'Tega Cay', 'York', 'Clover', 'Charlotte'] },
    { city: 'Greenville', citySlug: 'greenville', county: 'Greenville County', lat: 34.8526, lng: -82.3940, surroundingCities: ['Greer', 'Mauldin', 'Simpsonville', 'Taylors', 'Easley'] },
    { city: 'Summerville', citySlug: 'summerville', county: 'Dorchester County', lat: 33.0185, lng: -80.1756, surroundingCities: ['North Charleston', 'Goose Creek', 'Ladson', 'Moncks Corner'] },
    { city: 'Sumter', citySlug: 'sumter', county: 'Sumter County', lat: 33.9204, lng: -80.3415, surroundingCities: ['Florence', 'Camden', 'Manning', 'Bishopville'] },
    { city: 'Goose Creek', citySlug: 'goose-creek', county: 'Berkeley County', lat: 32.9810, lng: -80.0326, surroundingCities: ['North Charleston', 'Hanahan', 'Summerville', 'Moncks Corner', 'Ladson'] },
    { city: 'Hilton Head Island', citySlug: 'hilton-head-island', county: 'Beaufort County', lat: 32.2163, lng: -80.7526, surroundingCities: ['Bluffton', 'Beaufort', 'Hardeeville', 'Port Royal'] },
    { city: 'Florence', citySlug: 'florence', county: 'Florence County', lat: 34.1954, lng: -79.7626, surroundingCities: ['Darlington', 'Hartsville', 'Marion', 'Lake City'] },
    { city: 'Spartanburg', citySlug: 'spartanburg', county: 'Spartanburg County', lat: 34.9496, lng: -81.9320, surroundingCities: ['Greer', 'Boiling Springs', 'Duncan', 'Wellford', 'Greenville'] },
    { city: 'Myrtle Beach', citySlug: 'myrtle-beach', county: 'Horry County', lat: 33.6891, lng: -78.8867, surroundingCities: ['North Myrtle Beach', 'Conway', 'Surfside Beach', 'Socastee'] },
    { city: 'Aiken', citySlug: 'aiken', county: 'Aiken County', lat: 33.5604, lng: -81.7196, surroundingCities: ['North Augusta', 'Graniteville', 'Augusta', 'Belvedere'] },
    { city: 'Greer', citySlug: 'greer', county: 'Greenville County', lat: 34.9387, lng: -82.2270, surroundingCities: ['Greenville', 'Taylors', 'Spartanburg', 'Duncan', 'Mauldin'] },
    { city: 'Anderson', citySlug: 'anderson', county: 'Anderson County', lat: 34.5034, lng: -82.6501, surroundingCities: ['Easley', 'Clemson', 'Pendleton', 'Williamston', 'Belton'] },
    { city: 'Mauldin', citySlug: 'mauldin', county: 'Greenville County', lat: 34.7790, lng: -82.3076, surroundingCities: ['Greenville', 'Simpsonville', 'Greer', 'Five Forks', 'Fountain Inn'] },
    { city: 'Greenwood', citySlug: 'greenwood', county: 'Greenwood County', lat: 34.1954, lng: -82.1618, surroundingCities: ['Abbeville', 'Ninety Six', 'Laurens', 'Clinton'] },
    { city: 'North Augusta', citySlug: 'north-augusta', county: 'Aiken County', lat: 33.5018, lng: -81.9651, surroundingCities: ['Aiken', 'Augusta', 'Belvedere', 'Graniteville'] },
    { city: 'Hanahan', citySlug: 'hanahan', county: 'Berkeley County', lat: 32.9182, lng: -80.0220, surroundingCities: ['North Charleston', 'Goose Creek', 'Charleston', 'Ladson'] },
    { city: 'Simpsonville', citySlug: 'simpsonville', county: 'Greenville County', lat: 34.7370, lng: -82.2543, surroundingCities: ['Mauldin', 'Fountain Inn', 'Five Forks', 'Greenville', 'Greer'] },
    { city: 'Easley', citySlug: 'easley', county: 'Pickens County', lat: 34.8298, lng: -82.6015, surroundingCities: ['Greenville', 'Pickens', 'Liberty', 'Powdersville', 'Anderson'] },
    { city: 'Bluffton', citySlug: 'bluffton', county: 'Beaufort County', lat: 32.2371, lng: -80.8604, surroundingCities: ['Hilton Head Island', 'Beaufort', 'Hardeeville', 'Port Royal'] },
    { city: 'Conway', citySlug: 'conway', county: 'Horry County', lat: 33.8360, lng: -79.0478, surroundingCities: ['Myrtle Beach', 'Socastee', 'Aynor', 'North Myrtle Beach'] },
    { city: 'Lexington', citySlug: 'lexington', county: 'Lexington County', lat: 33.9815, lng: -81.2362, surroundingCities: ['West Columbia', 'Cayce', 'Columbia', 'Irmo', 'Gilbert'] },
    { city: 'North Myrtle Beach', citySlug: 'north-myrtle-beach', county: 'Horry County', lat: 33.8160, lng: -78.6800, surroundingCities: ['Myrtle Beach', 'Conway', 'Little River', 'Loris'] },
    { city: 'Socastee', citySlug: 'socastee', county: 'Horry County', lat: 33.6857, lng: -79.0086, surroundingCities: ['Myrtle Beach', 'Conway', 'Surfside Beach', 'Forestbrook'] },
    { city: 'Taylors', citySlug: 'taylors', county: 'Greenville County', lat: 34.9237, lng: -82.2957, surroundingCities: ['Greenville', 'Greer', 'Wade Hampton', 'Mauldin'] },
    { city: 'St. Andrews', citySlug: 'st-andrews', county: 'Richland County', lat: 34.0488, lng: -81.1031, surroundingCities: ['Columbia', 'Irmo', 'Seven Oaks', 'West Columbia'] },
    { city: 'Five Forks', citySlug: 'five-forks', county: 'Greenville County', lat: 34.8048, lng: -82.2296, surroundingCities: ['Simpsonville', 'Mauldin', 'Greer', 'Greenville'] },
    { city: 'Wade Hampton', citySlug: 'wade-hampton', county: 'Greenville County', lat: 34.8835, lng: -82.3382, surroundingCities: ['Greenville', 'Taylors', 'Greer', 'Mauldin'] },
    { city: 'Fort Mill', citySlug: 'fort-mill', county: 'York County', lat: 35.0074, lng: -80.9451, surroundingCities: ['Rock Hill', 'Tega Cay', 'Indian Land', 'Charlotte'] },
    { city: 'Cayce', citySlug: 'cayce', county: 'Lexington County', lat: 33.9624, lng: -81.0737, surroundingCities: ['West Columbia', 'Columbia', 'Lexington', 'Springdale'] },
    { city: 'West Columbia', citySlug: 'west-columbia', county: 'Lexington County', lat: 33.9935, lng: -81.0739, surroundingCities: ['Cayce', 'Columbia', 'Lexington', 'Springdale'] },
    { city: 'Beaufort', citySlug: 'beaufort', county: 'Beaufort County', lat: 32.4316, lng: -80.6698, surroundingCities: ['Port Royal', 'Bluffton', 'Hilton Head Island', 'Burton'] },
    { city: 'Irmo', citySlug: 'irmo', county: 'Richland County', lat: 34.0857, lng: -81.1832, surroundingCities: ['Columbia', 'St. Andrews', 'Lexington', 'Chapin', 'Seven Oaks'] },
    { city: 'Clemson', citySlug: 'clemson', county: 'Pickens County', lat: 34.6834, lng: -82.8374, surroundingCities: ['Central', 'Pendleton', 'Seneca', 'Easley', 'Anderson'] },
    { city: 'Tega Cay', citySlug: 'tega-cay', county: 'York County', lat: 35.0243, lng: -81.0279, surroundingCities: ['Fort Mill', 'Rock Hill', 'Lake Wylie', 'Clover'] },
    { city: 'Hartsville', citySlug: 'hartsville', county: 'Darlington County', lat: 34.3740, lng: -80.0731, surroundingCities: ['Darlington', 'Florence', 'Bishopville', 'Society Hill'] },
    { city: 'Orangeburg', citySlug: 'orangeburg', county: 'Orangeburg County', lat: 33.4918, lng: -80.8557, surroundingCities: ['Santee', 'St. Matthews', 'Bamberg', 'Holly Hill'] },
    { city: 'Forest Acres', citySlug: 'forest-acres', county: 'Richland County', lat: 34.0224, lng: -80.9912, surroundingCities: ['Columbia', 'Dentsville', 'Arcadia Lakes', 'St. Andrews'] },
  ],
  indiana: [
    { city: 'Indianapolis', citySlug: 'indianapolis', county: 'Marion County', lat: 39.7684, lng: -86.1581, surroundingCities: ['Carmel', 'Fishers', 'Greenwood', 'Lawrence', 'Beech Grove'] },
    { city: 'Fort Wayne', citySlug: 'fort-wayne', county: 'Allen County', lat: 41.0793, lng: -85.1394, surroundingCities: ['New Haven', 'Huntertown', 'Auburn', 'Columbia City', 'Bluffton'] },
    { city: 'Evansville', citySlug: 'evansville', county: 'Vanderburgh County', lat: 37.9716, lng: -87.5711, surroundingCities: ['Newburgh', 'Boonville', 'Henderson', 'Mount Vernon', 'Princeton'] },
    { city: 'Carmel', citySlug: 'carmel', county: 'Hamilton County', lat: 39.9784, lng: -86.1180, surroundingCities: ['Fishers', 'Westfield', 'Noblesville', 'Zionsville', 'Indianapolis'] },
    { city: 'South Bend', citySlug: 'south-bend', county: 'St. Joseph County', lat: 41.6764, lng: -86.2520, surroundingCities: ['Mishawaka', 'Granger', 'Elkhart', 'Goshen', 'Niles'] },
    { city: 'Fishers', citySlug: 'fishers', county: 'Hamilton County', lat: 39.9568, lng: -85.9685, surroundingCities: ['Carmel', 'Noblesville', 'Lawrence', 'Westfield', 'McCordsville'] },
    { city: 'Bloomington', citySlug: 'bloomington', county: 'Monroe County', lat: 39.1653, lng: -86.5264, surroundingCities: ['Ellettsville', 'Bedford', 'Martinsville', 'Spencer', 'Nashville'] },
    { city: 'Hammond', citySlug: 'hammond', county: 'Lake County', lat: 41.5834, lng: -87.5000, surroundingCities: ['Munster', 'Highland', 'Whiting', 'East Chicago', 'Griffith'] },
    { city: 'Noblesville', citySlug: 'noblesville', county: 'Hamilton County', lat: 40.0456, lng: -86.0086, surroundingCities: ['Fishers', 'Westfield', 'Carmel', 'Cicero', 'McCordsville'] },
    { city: 'Gary', citySlug: 'gary', county: 'Lake County', lat: 41.5934, lng: -87.3464, surroundingCities: ['Hobart', 'Merrillville', 'Hammond', 'Lake Station', 'Portage'] },
    { city: 'Lafayette', citySlug: 'lafayette', county: 'Tippecanoe County', lat: 40.4167, lng: -86.8753, surroundingCities: ['West Lafayette', 'Dayton', 'Battle Ground', 'Crawfordsville', 'Frankfort'] },
    { city: 'Greenwood', citySlug: 'greenwood', county: 'Johnson County', lat: 39.6137, lng: -86.1067, surroundingCities: ['Franklin', 'Indianapolis', 'Beech Grove', 'Bargersville', 'Whiteland'] },
    { city: 'Muncie', citySlug: 'muncie', county: 'Delaware County', lat: 40.1934, lng: -85.3864, surroundingCities: ['Anderson', 'Yorktown', 'Marion', 'New Castle', 'Hartford City'] },
    { city: 'Westfield', citySlug: 'westfield', county: 'Hamilton County', lat: 40.0428, lng: -86.1275, surroundingCities: ['Carmel', 'Noblesville', 'Fishers', 'Zionsville', 'Sheridan'] },
    { city: 'Terre Haute', citySlug: 'terre-haute', county: 'Vigo County', lat: 39.4667, lng: -87.4139, surroundingCities: ['Brazil', 'Clinton', 'Sullivan', 'Rockville', 'Marshall'] },
    { city: 'Kokomo', citySlug: 'kokomo', county: 'Howard County', lat: 40.4864, lng: -86.1336, surroundingCities: ['Peru', 'Marion', 'Logansport', 'Tipton', 'Greentown'] },
    { city: 'Anderson', citySlug: 'anderson', county: 'Madison County', lat: 40.1053, lng: -85.6803, surroundingCities: ['Muncie', 'Pendleton', 'Elwood', 'Alexandria', 'Noblesville'] },
    { city: 'Mishawaka', citySlug: 'mishawaka', county: 'St. Joseph County', lat: 41.6620, lng: -86.1586, surroundingCities: ['South Bend', 'Granger', 'Elkhart', 'Osceola', 'Goshen'] },
    { city: 'Elkhart', citySlug: 'elkhart', county: 'Elkhart County', lat: 41.6819, lng: -85.9767, surroundingCities: ['Goshen', 'Mishawaka', 'Granger', 'Bristol', 'Nappanee'] },
    { city: 'Lawrence', citySlug: 'lawrence', county: 'Marion County', lat: 39.8387, lng: -86.0252, surroundingCities: ['Indianapolis', 'Fishers', 'McCordsville', 'Beech Grove', 'Carmel'] },
    { city: 'Columbus', citySlug: 'columbus', county: 'Bartholomew County', lat: 39.2014, lng: -85.9214, surroundingCities: ['Seymour', 'Greensburg', 'Franklin', 'North Vernon', 'Edinburgh'] },
    { city: 'Jeffersonville', citySlug: 'jeffersonville', county: 'Clark County', lat: 38.2776, lng: -85.7372, surroundingCities: ['Clarksville', 'New Albany', 'Louisville', 'Sellersburg', 'Charlestown'] },
    { city: 'Portage', citySlug: 'portage', county: 'Porter County', lat: 41.5759, lng: -87.1761, surroundingCities: ['Valparaiso', 'Chesterton', 'Hobart', 'Lake Station', 'Gary'] },
    { city: 'New Albany', citySlug: 'new-albany', county: 'Floyd County', lat: 38.2856, lng: -85.8241, surroundingCities: ['Jeffersonville', 'Clarksville', 'Louisville', 'Georgetown', 'Sellersburg'] },
    { city: 'Richmond', citySlug: 'richmond', county: 'Wayne County', lat: 39.8289, lng: -84.8902, surroundingCities: ['Connersville', 'Cambridge City', 'New Castle', 'Centerville', 'Hagerstown'] },
    { city: 'West Lafayette', citySlug: 'west-lafayette', county: 'Tippecanoe County', lat: 40.4259, lng: -86.9081, surroundingCities: ['Lafayette', 'Battle Ground', 'Dayton', 'Monticello', 'Delphi'] },
    { city: 'Valparaiso', citySlug: 'valparaiso', county: 'Porter County', lat: 41.4731, lng: -87.0611, surroundingCities: ['Portage', 'Chesterton', 'Hobart', 'Crown Point', 'Hebron'] },
    { city: 'Goshen', citySlug: 'goshen', county: 'Elkhart County', lat: 41.5820, lng: -85.8344, surroundingCities: ['Elkhart', 'Nappanee', 'Middlebury', 'Mishawaka', 'Warsaw'] },
    { city: 'Michigan City', citySlug: 'michigan-city', county: 'LaPorte County', lat: 41.7075, lng: -86.8950, surroundingCities: ['La Porte', 'Chesterton', 'Portage', 'Valparaiso', 'New Buffalo'] },
    { city: 'Crown Point', citySlug: 'crown-point', county: 'Lake County', lat: 41.4170, lng: -87.3653, surroundingCities: ['Merrillville', 'Schererville', 'Cedar Lake', 'Hobart', 'Saint John'] },
    { city: 'Hobart', citySlug: 'hobart', county: 'Lake County', lat: 41.5320, lng: -87.2548, surroundingCities: ['Merrillville', 'Portage', 'Lake Station', 'Gary', 'Valparaiso'] },
    { city: 'Merrillville', citySlug: 'merrillville', county: 'Lake County', lat: 41.4828, lng: -87.3328, surroundingCities: ['Crown Point', 'Hobart', 'Schererville', 'Gary', 'Griffith'] },
    { city: 'Schererville', citySlug: 'schererville', county: 'Lake County', lat: 41.4789, lng: -87.4548, surroundingCities: ['Merrillville', 'Crown Point', 'Dyer', 'Saint John', 'Highland'] },
    { city: 'Plainfield', citySlug: 'plainfield', county: 'Hendricks County', lat: 39.7042, lng: -86.3994, surroundingCities: ['Avon', 'Brownsburg', 'Danville', 'Mooresville', 'Indianapolis'] },
    { city: 'Brownsburg', citySlug: 'brownsburg', county: 'Hendricks County', lat: 39.8434, lng: -86.3978, surroundingCities: ['Avon', 'Plainfield', 'Danville', 'Zionsville', 'Pittsboro'] },
    { city: 'Franklin', citySlug: 'franklin', county: 'Johnson County', lat: 39.4806, lng: -86.0550, surroundingCities: ['Greenwood', 'Whiteland', 'Edinburgh', 'Bargersville', 'Shelbyville'] },
    { city: 'Marion', citySlug: 'marion', county: 'Grant County', lat: 40.5584, lng: -85.6591, surroundingCities: ['Gas City', 'Hartford City', 'Kokomo', 'Wabash', 'Upland'] },
    { city: 'Zionsville', citySlug: 'zionsville', county: 'Boone County', lat: 39.9509, lng: -86.2619, surroundingCities: ['Carmel', 'Brownsburg', 'Whitestown', 'Lebanon', 'Westfield'] },
    { city: 'Highland', citySlug: 'highland', county: 'Lake County', lat: 41.5534, lng: -87.4520, surroundingCities: ['Munster', 'Griffith', 'Hammond', 'Schererville', 'Dyer'] },
    { city: 'Munster', citySlug: 'munster', county: 'Lake County', lat: 41.5642, lng: -87.5128, surroundingCities: ['Highland', 'Hammond', 'Dyer', 'Schererville', 'Griffith'] },
    { city: 'Shelbyville', citySlug: 'shelbyville', county: 'Shelby County', lat: 39.5217, lng: -85.7769, surroundingCities: ['Franklin', 'Greenfield', 'Greensburg', 'Rushville', 'Morristown'] },
    { city: 'Seymour', citySlug: 'seymour', county: 'Jackson County', lat: 38.9592, lng: -85.8903, surroundingCities: ['Columbus', 'North Vernon', 'Brownstown', 'Scottsburg', 'Crothersville'] },
    { city: 'Greenfield', citySlug: 'greenfield', county: 'Hancock County', lat: 39.7847, lng: -85.7694, surroundingCities: ['McCordsville', 'Fortville', 'Shelbyville', 'Lawrence', 'Pendleton'] },
    { city: 'Vincennes', citySlug: 'vincennes', county: 'Knox County', lat: 38.6773, lng: -87.5286, surroundingCities: ['Bicknell', 'Washington', 'Princeton', 'Petersburg', 'Lawrenceville'] },
    { city: 'Crawfordsville', citySlug: 'crawfordsville', county: 'Montgomery County', lat: 40.0411, lng: -86.8744, surroundingCities: ['Lebanon', 'Frankfort', 'Lafayette', 'Greencastle', 'Veedersburg'] },
    { city: 'New Castle', citySlug: 'new-castle', county: 'Henry County', lat: 39.9286, lng: -85.3702, surroundingCities: ['Muncie', 'Knightstown', 'Richmond', 'Hagerstown', 'Anderson'] },
    { city: 'Frankfort', citySlug: 'frankfort', county: 'Clinton County', lat: 40.2806, lng: -86.5108, surroundingCities: ['Lebanon', 'Lafayette', 'Kokomo', 'Crawfordsville', 'Tipton'] },
    { city: 'Lebanon', citySlug: 'lebanon', county: 'Boone County', lat: 40.0481, lng: -86.4692, surroundingCities: ['Zionsville', 'Whitestown', 'Frankfort', 'Crawfordsville', 'Thorntown'] },
    { city: 'La Porte', citySlug: 'la-porte', county: 'LaPorte County', lat: 41.6106, lng: -86.7228, surroundingCities: ['Michigan City', 'Valparaiso', 'Chesterton', 'Westville', 'Wanatah'] },
    { city: 'Clarksville', citySlug: 'clarksville', county: 'Clark County', lat: 38.2967, lng: -85.7600, surroundingCities: ['Jeffersonville', 'New Albany', 'Sellersburg', 'Louisville', 'Charlestown'] },
  ],
};
